events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

    upstream study_groups_backend { server payara:8181; }
    upstream isu_backend { server wildfly:8443; }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /etc/nginx/tls/server.crt;
        ssl_certificate_key /etc/nginx/tls/server.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        proxy_ssl_trusted_certificate /etc/nginx/tls/server.crt;
        proxy_ssl_verify on;
        proxy_ssl_server_name on;

        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass https://study_groups_backend;
            proxy_ssl_name payara;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /isu/ {
            proxy_pass https://isu_backend;
            proxy_ssl_name wildfly;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location = /swagger-ui.html {
            proxy_pass https://study_groups_backend/swagger-ui.html;
            proxy_ssl_name payara;
        }

        location = /openapi.yaml {
            proxy_pass https://study_groups_backend/openapi.yaml;
            proxy_ssl_name payara;
        }

        location /webjars/ {
            proxy_pass https://study_groups_backend;
            proxy_ssl_name payara;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
